export const SET_LOADING = 'SET_LOADING';
export const SET_NOT_FOUND = 'SET_NOT_FOUND';
export const SET_PREVIOUS_LOCATION = 'SET_PREVIOUS_LOCATION';

export const SET_SUBMIT_SUCCESS = 'SET_SUBMIT_SUCCESS';
export const SET_SUBMIT_ERRORS = 'SET_SUBMIT_ERRORS';
export const UNSET_SUBMIT = 'UNSET_SUBMIT';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_CONFIRM = 'SIGN_UP_CONFIRM';
export const UNSET_CURRENT_UNCONFIRMED_USER = 'UNSET_CURRENT_UNCONFIRMED_USER';
export const LOGOUT = 'LOGOUT';
export const AUTHENTICATE = 'AUTHENTICATE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UNSET_CURRENT_USER = 'UNSET_CURRENT_USER';
export const ESTABLISH_CURRENT_USER = 'ESTABLISH_CURRENT_USER';

export const GET_WORLDS = 'GET_WORLDS';
export const SET_WORLDS = 'SET_WORLDS';
export const CREATE_WORLD = 'CREATE_WORLD';
export const UPDATE_WORLD = 'UPDATE_WORLD';
export const UPDATE_WORLD_SUCCESS = 'UPDATE_WORLD_SUCCESS';
export const UPDATE_WORLD_ERROR = 'UPDATE_WORLD_ERROR';
export const GET_WORLD = 'GET_WORLD';
export const SET_WORLD = 'SET_WORLD';
export const UNSET_WORLD = 'UNSET_WORLD';
export const SEARCH_ALL = 'SEARCH_ALL';

export const SET_SEARCH_LOADING = 'SET_SEARCH_LOADING';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const UNSET_SEARCH_RESULTS = 'UNSET_SEARCH_RESULTS';

export const CREATE_WORLD_SUBMIT = 'CREATE_WORLD_SUBMIT';
export const UPDATE_WORLD_SUBMIT = 'UPDATE_WORLD_SUBMIT';
