export const SET_LOADING = 'SET_LOADING';
export const SET_NOT_FOUND = 'SET_NOT_FOUND';
export const SET_PREVIOUS_LOCATION = 'SET_PREVIOUS_LOCATION';

export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const SIGN_UP_CONFIRM = 'SIGN_UP_CONFIRM';
export const SIGN_UP_CONFIRM_SUCCESS = 'SIGN_UP_CONFIRM_SUCCESS';
export const SIGN_UP_CONFIRM_ERROR = 'SIGN_UP_CONFIRM_ERROR';
export const SET_CURRENT_UNCONFIRMED_USER = 'SET_CURRENT_UNCONFIRMED_USER';
export const UNSET_CURRENT_UNCONFIRMED_USER = 'UNSET_CURRENT_UNCONFIRMED_USER';
export const SIGN_OUT = 'SIGN_OUT';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UNSET_CURRENT_USER = 'UNSET_CURRENT_USER';

export const SEARCH_ALL = 'SEARCH_ALL';

export const LIST_WORLDS = 'LIST_WORLDS';
export const LIST_WORLDS_SUCCESS = 'LIST_WORLDS_SUCCESS';
export const LIST_WORLDS_ERROR = 'LIST_WORLDS_ERROR';
export const SET_WORLDS = 'SET_WORLDS';
export const CREATE_WORLD = 'CREATE_WORLD';
export const CREATE_WORLD_SUCCESS = 'CREATE_WORLD_SUCCESS';
export const CREATE_WORLD_ERROR = 'CREATE_WORLD_ERROR';
export const UPDATE_WORLD = 'UPDATE_WORLD';
export const UPDATE_WORLD_SUCCESS = 'UPDATE_WORLD_SUCCESS';
export const UPDATE_WORLD_ERROR = 'UPDATE_WORLD_ERROR';
export const GET_WORLD = 'GET_WORLD';
export const GET_WORLD_SUCCESS = 'GET_WORLD_SUCCESS';
export const GET_WORLD_ERROR = 'GET_WORLD_ERROR';
export const SET_WORLD = 'SET_WORLD';
export const UNSET_WORLD = 'UNSET_WORLD';

export const CREATE_GAME = 'CREATE_GAME';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_ERROR = 'CREATE_GAME_ERROR';
export const UPDATE_GAME = 'UPDATE_GAME';
export const UPDATE_GAME_SUCCESS = 'UPDATE_GAME_SUCCESS';
export const UPDATE_GAME_ERROR = 'UPDATE_GAME_ERROR';
export const GET_GAME = 'GET_GAME';
export const GET_GAME_SUCCESS = 'GET_GAME_SUCCESS';
export const GET_GAME_ERROR = 'GET_GAME_ERROR';
export const SET_GAME = 'SET_GAME';
export const UNSET_GAME = 'UNSET_GAME';

export const SET_SEARCH_LOADING = 'SET_SEARCH_LOADING';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const UNSET_SEARCH_RESULTS = 'UNSET_SEARCH_RESULTS';

export const LOAD_WORLDS = 'LOAD_WORLDS';
export const LOAD_WORLD = 'LOAD_WORLD';
export const LOAD_GAME = 'LOAD_GAME';

export const AUTHENTICATE_SYNC = 'AUTHENTICATE_SYNC';
export const SIGN_IN_SYNC = 'SIGN_IN_SYNC';
export const SIGN_UP_SYNC = 'SIGN_UP_SYNC';
export const SIGN_UP_CONFIRM_SYNC = 'SIGN_UP_CONFIRM_SYNC';
export const CREATE_WORLD_SYNC = 'CREATE_WORLD_SYNC';
export const UPDATE_WORLD_SYNC = 'UPDATE_WORLD_SYNC';
export const CREATE_GAME_SYNC = 'CREATE_GAME_SYNC';
export const UPDATE_GAME_SYNC = 'UPDATE_GAME_SYNC';
export const GET_CURRENT_LANGUAGE_SYNC = 'GET_CURRENT_LANGUAGE_SYNC';

export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR';

export const SET_CURRENT_LANGUAGE = 'SET_CURRENT_LANGUAGE';
export const SET_CURRENT_LANGUAGE_SUCCESS = 'SET_CURRENT_LANGUAGE_SUCCESS';
export const SET_CURRENT_LANGUAGE_ERROR = 'SET_CURRENT_LANGUAGE_ERROR';
export const GET_CURRENT_LANGUAGE = 'GET_CURRENT_LANGUAGE';
export const GET_CURRENT_LANGUAGE_SUCCESS = 'GET_CURRENT_LANGUAGE_SUCCESS';
export const GET_CURRENT_LANGUAGE_ERROR = 'GET_CURRENT_LANGUAGE_ERROR';
