export const SET_LOADING = 'SET_LOADING';
export const SET_NOT_FOUND = 'SET_NOT_FOUND';

export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const COMPLETE_UPDATE_COUNTER = 'COMPLETE_UPDATE_COUNTER';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_CONFIRM = 'SIGN_UP_CONFIRM';
export const UNSET_CURRENT_UNCONFIRMED_USER = 'UNSET_CURRENT_UNCONFIRMED_USER';
export const LOGOUT = 'LOGOUT';
export const AUTHENTICATE = 'AUTHENTICATE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UNSET_CURRENT_USER = 'UNSET_CURRENT_USER';
export const ESTABLISH_CURRENT_USER = 'ESTABLISH_CURRENT_USER';

export const GET_CURRENT_PROFILE = 'GET_CURRENT_PROFILE';
export const SET_CURRENT_PROFILE = 'SET_CURRENT_PROFILE';
export const UNSET_CURRENT_PROFILE = 'UNSET_CURRENT_PROFILE';
