// flow-typed signature: 57489196b07657f8e31fceef85e6597b
// flow-typed version: <<STUB>>/aws-amplify-react_v2.3.6/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aws-amplify-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aws-amplify-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aws-amplify-react/dist/Amplify-UI/Amplify-UI-Components-React' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Amplify-UI/Amplify-UI-Theme-Sample' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Amplify-UI/Amplify-UI-Theme' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/AmplifyI18n' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/AmplifyMessageMap' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/AmplifyTheme' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/AmplifyUI' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Analytics/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Analytics/trackLifecycle' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Analytics/trackUpdate' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/API/GraphQL/Connect' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/API/GraphQL/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/API/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/Authenticator' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/AuthPiece' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/AuthStateWrapper' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/common/constants' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/common/country-dial-codes' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/common/default-sign-in-fields' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/ConfirmSignIn' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/ConfirmSignUp' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/FederatedSignIn' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/ForgotPassword' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/Greetings' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/Loading' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/Provider/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/Provider/withAmazon' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/Provider/withAuth0' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/Provider/withFacebook' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/Provider/withGoogle' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/Provider/withOAuth' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/RequireNewPassword' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/SignIn' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/SignOut' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/SignUp' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/TOTPSetup' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/VerifyContact' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Interactions/aws-lex-audio' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Interactions/ChatBot' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Interactions/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Storage/Common' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Storage/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Storage/S3Album' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Storage/S3Image' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Storage/S3Text' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Widget/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Widget/PhotoPicker' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Widget/Picker' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Widget/SelectMFAType' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Widget/TextPicker' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Widget/TOTPSetupComp' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/XR/IconButton' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/XR/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/XR/Loading' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/XR/SumerianScene' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/XR/Tooltip' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Amplify-UI/Amplify-UI-Components-React' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Amplify-UI/Amplify-UI-Theme-Sample' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Amplify-UI/Amplify-UI-Theme' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/AmplifyI18n' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/AmplifyMessageMap' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/AmplifyTheme' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/AmplifyUI' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Analytics/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Analytics/trackLifecycle' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Analytics/trackUpdate' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/API/GraphQL/Connect' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/API/GraphQL/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/API/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/Authenticator' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/AuthPiece' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/AuthStateWrapper' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/common/constants' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/common/country-dial-codes' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/common/default-sign-in-fields' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/ConfirmSignIn' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/ConfirmSignUp' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/FederatedSignIn' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/ForgotPassword' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/Greetings' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/Loading' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/Provider/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/Provider/withAmazon' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/Provider/withAuth0' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/Provider/withFacebook' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/Provider/withGoogle' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/Provider/withOAuth' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/RequireNewPassword' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/SignIn' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/SignOut' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/SignUp' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/TOTPSetup' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Auth/VerifyContact' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Interactions/aws-lex-audio' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Interactions/ChatBot' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Interactions/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Storage/Common' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Storage/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Storage/S3Album' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Storage/S3Image' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Storage/S3Text' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Widget/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Widget/PhotoPicker' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Widget/Picker' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Widget/SelectMFAType' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Widget/TextPicker' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/Widget/TOTPSetupComp' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/XR/IconButton' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/XR/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/XR/Loading' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/XR/SumerianScene' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/src/XR/Tooltip' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aws-amplify-react/dist/Amplify-UI/Amplify-UI-Components-React.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Amplify-UI/Amplify-UI-Components-React'>;
}
declare module 'aws-amplify-react/dist/Amplify-UI/Amplify-UI-Theme-Sample.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Amplify-UI/Amplify-UI-Theme-Sample'>;
}
declare module 'aws-amplify-react/dist/Amplify-UI/Amplify-UI-Theme.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Amplify-UI/Amplify-UI-Theme'>;
}
declare module 'aws-amplify-react/dist/AmplifyI18n.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/AmplifyI18n'>;
}
declare module 'aws-amplify-react/dist/AmplifyMessageMap.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/AmplifyMessageMap'>;
}
declare module 'aws-amplify-react/dist/AmplifyTheme.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/AmplifyTheme'>;
}
declare module 'aws-amplify-react/dist/AmplifyUI.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/AmplifyUI'>;
}
declare module 'aws-amplify-react/dist/Analytics/index.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Analytics/index'>;
}
declare module 'aws-amplify-react/dist/Analytics/trackLifecycle.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Analytics/trackLifecycle'>;
}
declare module 'aws-amplify-react/dist/Analytics/trackUpdate.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Analytics/trackUpdate'>;
}
declare module 'aws-amplify-react/dist/API/GraphQL/Connect.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/API/GraphQL/Connect'>;
}
declare module 'aws-amplify-react/dist/API/GraphQL/index.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/API/GraphQL/index'>;
}
declare module 'aws-amplify-react/dist/API/index.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/API/index'>;
}
declare module 'aws-amplify-react/dist/Auth/Authenticator.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/Authenticator'>;
}
declare module 'aws-amplify-react/dist/Auth/AuthPiece.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/AuthPiece'>;
}
declare module 'aws-amplify-react/dist/Auth/AuthStateWrapper.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/AuthStateWrapper'>;
}
declare module 'aws-amplify-react/dist/Auth/common/constants.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/common/constants'>;
}
declare module 'aws-amplify-react/dist/Auth/common/country-dial-codes.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/common/country-dial-codes'>;
}
declare module 'aws-amplify-react/dist/Auth/common/default-sign-in-fields.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/common/default-sign-in-fields'>;
}
declare module 'aws-amplify-react/dist/Auth/ConfirmSignIn.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/ConfirmSignIn'>;
}
declare module 'aws-amplify-react/dist/Auth/ConfirmSignUp.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/ConfirmSignUp'>;
}
declare module 'aws-amplify-react/dist/Auth/FederatedSignIn.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/FederatedSignIn'>;
}
declare module 'aws-amplify-react/dist/Auth/ForgotPassword.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/ForgotPassword'>;
}
declare module 'aws-amplify-react/dist/Auth/Greetings.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/Greetings'>;
}
declare module 'aws-amplify-react/dist/Auth/index.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/index'>;
}
declare module 'aws-amplify-react/dist/Auth/Loading.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/Loading'>;
}
declare module 'aws-amplify-react/dist/Auth/Provider/index.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/Provider/index'>;
}
declare module 'aws-amplify-react/dist/Auth/Provider/withAmazon.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/Provider/withAmazon'>;
}
declare module 'aws-amplify-react/dist/Auth/Provider/withAuth0.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/Provider/withAuth0'>;
}
declare module 'aws-amplify-react/dist/Auth/Provider/withFacebook.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/Provider/withFacebook'>;
}
declare module 'aws-amplify-react/dist/Auth/Provider/withGoogle.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/Provider/withGoogle'>;
}
declare module 'aws-amplify-react/dist/Auth/Provider/withOAuth.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/Provider/withOAuth'>;
}
declare module 'aws-amplify-react/dist/Auth/RequireNewPassword.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/RequireNewPassword'>;
}
declare module 'aws-amplify-react/dist/Auth/SignIn.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/SignIn'>;
}
declare module 'aws-amplify-react/dist/Auth/SignOut.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/SignOut'>;
}
declare module 'aws-amplify-react/dist/Auth/SignUp.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/SignUp'>;
}
declare module 'aws-amplify-react/dist/Auth/TOTPSetup.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/TOTPSetup'>;
}
declare module 'aws-amplify-react/dist/Auth/VerifyContact.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/VerifyContact'>;
}
declare module 'aws-amplify-react/dist/index.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/index'>;
}
declare module 'aws-amplify-react/dist/Interactions/aws-lex-audio.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Interactions/aws-lex-audio'>;
}
declare module 'aws-amplify-react/dist/Interactions/ChatBot.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Interactions/ChatBot'>;
}
declare module 'aws-amplify-react/dist/Interactions/index.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Interactions/index'>;
}
declare module 'aws-amplify-react/dist/Storage/Common.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Storage/Common'>;
}
declare module 'aws-amplify-react/dist/Storage/index.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Storage/index'>;
}
declare module 'aws-amplify-react/dist/Storage/S3Album.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Storage/S3Album'>;
}
declare module 'aws-amplify-react/dist/Storage/S3Image.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Storage/S3Image'>;
}
declare module 'aws-amplify-react/dist/Storage/S3Text.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Storage/S3Text'>;
}
declare module 'aws-amplify-react/dist/Widget/index.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Widget/index'>;
}
declare module 'aws-amplify-react/dist/Widget/PhotoPicker.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Widget/PhotoPicker'>;
}
declare module 'aws-amplify-react/dist/Widget/Picker.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Widget/Picker'>;
}
declare module 'aws-amplify-react/dist/Widget/SelectMFAType.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Widget/SelectMFAType'>;
}
declare module 'aws-amplify-react/dist/Widget/TextPicker.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Widget/TextPicker'>;
}
declare module 'aws-amplify-react/dist/Widget/TOTPSetupComp.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Widget/TOTPSetupComp'>;
}
declare module 'aws-amplify-react/dist/XR/IconButton.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/XR/IconButton'>;
}
declare module 'aws-amplify-react/dist/XR/index.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/XR/index'>;
}
declare module 'aws-amplify-react/dist/XR/Loading.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/XR/Loading'>;
}
declare module 'aws-amplify-react/dist/XR/SumerianScene.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/XR/SumerianScene'>;
}
declare module 'aws-amplify-react/dist/XR/Tooltip.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/XR/Tooltip'>;
}
declare module 'aws-amplify-react/src/Amplify-UI/Amplify-UI-Components-React.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Amplify-UI/Amplify-UI-Components-React'>;
}
declare module 'aws-amplify-react/src/Amplify-UI/Amplify-UI-Theme-Sample.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Amplify-UI/Amplify-UI-Theme-Sample'>;
}
declare module 'aws-amplify-react/src/Amplify-UI/Amplify-UI-Theme.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Amplify-UI/Amplify-UI-Theme'>;
}
declare module 'aws-amplify-react/src/AmplifyI18n.js' {
  declare module.exports: $Exports<'aws-amplify-react/src/AmplifyI18n'>;
}
declare module 'aws-amplify-react/src/AmplifyMessageMap.js' {
  declare module.exports: $Exports<'aws-amplify-react/src/AmplifyMessageMap'>;
}
declare module 'aws-amplify-react/src/AmplifyTheme.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/AmplifyTheme'>;
}
declare module 'aws-amplify-react/src/AmplifyUI.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/AmplifyUI'>;
}
declare module 'aws-amplify-react/src/Analytics/index.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Analytics/index'>;
}
declare module 'aws-amplify-react/src/Analytics/trackLifecycle.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Analytics/trackLifecycle'>;
}
declare module 'aws-amplify-react/src/Analytics/trackUpdate.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Analytics/trackUpdate'>;
}
declare module 'aws-amplify-react/src/API/GraphQL/Connect.js' {
  declare module.exports: $Exports<'aws-amplify-react/src/API/GraphQL/Connect'>;
}
declare module 'aws-amplify-react/src/API/GraphQL/index.js' {
  declare module.exports: $Exports<'aws-amplify-react/src/API/GraphQL/index'>;
}
declare module 'aws-amplify-react/src/API/index.js' {
  declare module.exports: $Exports<'aws-amplify-react/src/API/index'>;
}
declare module 'aws-amplify-react/src/Auth/Authenticator.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/Authenticator'>;
}
declare module 'aws-amplify-react/src/Auth/AuthPiece.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/AuthPiece'>;
}
declare module 'aws-amplify-react/src/Auth/AuthStateWrapper.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/AuthStateWrapper'>;
}
declare module 'aws-amplify-react/src/Auth/common/constants.js' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/common/constants'>;
}
declare module 'aws-amplify-react/src/Auth/common/country-dial-codes.js' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/common/country-dial-codes'>;
}
declare module 'aws-amplify-react/src/Auth/common/default-sign-in-fields.js' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/common/default-sign-in-fields'>;
}
declare module 'aws-amplify-react/src/Auth/ConfirmSignIn.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/ConfirmSignIn'>;
}
declare module 'aws-amplify-react/src/Auth/ConfirmSignUp.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/ConfirmSignUp'>;
}
declare module 'aws-amplify-react/src/Auth/FederatedSignIn.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/FederatedSignIn'>;
}
declare module 'aws-amplify-react/src/Auth/ForgotPassword.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/ForgotPassword'>;
}
declare module 'aws-amplify-react/src/Auth/Greetings.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/Greetings'>;
}
declare module 'aws-amplify-react/src/Auth/index.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/index'>;
}
declare module 'aws-amplify-react/src/Auth/Loading.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/Loading'>;
}
declare module 'aws-amplify-react/src/Auth/Provider/index.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/Provider/index'>;
}
declare module 'aws-amplify-react/src/Auth/Provider/withAmazon.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/Provider/withAmazon'>;
}
declare module 'aws-amplify-react/src/Auth/Provider/withAuth0.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/Provider/withAuth0'>;
}
declare module 'aws-amplify-react/src/Auth/Provider/withFacebook.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/Provider/withFacebook'>;
}
declare module 'aws-amplify-react/src/Auth/Provider/withGoogle.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/Provider/withGoogle'>;
}
declare module 'aws-amplify-react/src/Auth/Provider/withOAuth.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/Provider/withOAuth'>;
}
declare module 'aws-amplify-react/src/Auth/RequireNewPassword.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/RequireNewPassword'>;
}
declare module 'aws-amplify-react/src/Auth/SignIn.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/SignIn'>;
}
declare module 'aws-amplify-react/src/Auth/SignOut.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/SignOut'>;
}
declare module 'aws-amplify-react/src/Auth/SignUp.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/SignUp'>;
}
declare module 'aws-amplify-react/src/Auth/TOTPSetup.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/TOTPSetup'>;
}
declare module 'aws-amplify-react/src/Auth/VerifyContact.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Auth/VerifyContact'>;
}
declare module 'aws-amplify-react/src/index.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/index'>;
}
declare module 'aws-amplify-react/src/Interactions/aws-lex-audio.js' {
  declare module.exports: $Exports<'aws-amplify-react/src/Interactions/aws-lex-audio'>;
}
declare module 'aws-amplify-react/src/Interactions/ChatBot.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Interactions/ChatBot'>;
}
declare module 'aws-amplify-react/src/Interactions/index.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Interactions/index'>;
}
declare module 'aws-amplify-react/src/Storage/Common.js' {
  declare module.exports: $Exports<'aws-amplify-react/src/Storage/Common'>;
}
declare module 'aws-amplify-react/src/Storage/index.js' {
  declare module.exports: $Exports<'aws-amplify-react/src/Storage/index'>;
}
declare module 'aws-amplify-react/src/Storage/S3Album.js' {
  declare module.exports: $Exports<'aws-amplify-react/src/Storage/S3Album'>;
}
declare module 'aws-amplify-react/src/Storage/S3Image.js' {
  declare module.exports: $Exports<'aws-amplify-react/src/Storage/S3Image'>;
}
declare module 'aws-amplify-react/src/Storage/S3Text.js' {
  declare module.exports: $Exports<'aws-amplify-react/src/Storage/S3Text'>;
}
declare module 'aws-amplify-react/src/Widget/index.js' {
  declare module.exports: $Exports<'aws-amplify-react/src/Widget/index'>;
}
declare module 'aws-amplify-react/src/Widget/PhotoPicker.js' {
  declare module.exports: $Exports<'aws-amplify-react/src/Widget/PhotoPicker'>;
}
declare module 'aws-amplify-react/src/Widget/Picker.js' {
  declare module.exports: $Exports<'aws-amplify-react/src/Widget/Picker'>;
}
declare module 'aws-amplify-react/src/Widget/SelectMFAType.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Widget/SelectMFAType'>;
}
declare module 'aws-amplify-react/src/Widget/TextPicker.js' {
  declare module.exports: $Exports<'aws-amplify-react/src/Widget/TextPicker'>;
}
declare module 'aws-amplify-react/src/Widget/TOTPSetupComp.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/Widget/TOTPSetupComp'>;
}
declare module 'aws-amplify-react/src/XR/IconButton.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/XR/IconButton'>;
}
declare module 'aws-amplify-react/src/XR/index.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/XR/index'>;
}
declare module 'aws-amplify-react/src/XR/Loading.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/XR/Loading'>;
}
declare module 'aws-amplify-react/src/XR/SumerianScene.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/XR/SumerianScene'>;
}
declare module 'aws-amplify-react/src/XR/Tooltip.jsx' {
  declare module.exports: $Exports<'aws-amplify-react/src/XR/Tooltip'>;
}
