// flow-typed signature: c5e135410e5b923f45aa2937eb9a0f4f
// flow-typed version: <<STUB>>/md5-file_v4.0.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'md5-file'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'md5-file' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'md5-file/cli' {
  declare module.exports: any;
}

declare module 'md5-file/promise' {
  declare module.exports: any;
}

// Filename aliases
declare module 'md5-file/cli.js' {
  declare module.exports: $Exports<'md5-file/cli'>;
}
declare module 'md5-file/index' {
  declare module.exports: $Exports<'md5-file'>;
}
declare module 'md5-file/index.js' {
  declare module.exports: $Exports<'md5-file'>;
}
declare module 'md5-file/promise.js' {
  declare module.exports: $Exports<'md5-file/promise'>;
}
