// flow-typed signature: f21353e24824fe0c8a1667892f6b89f6
// flow-typed version: <<STUB>>/react-semantic-redux-form_v^1.2.6/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-semantic-redux-form'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-semantic-redux-form' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-semantic-redux-form/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-semantic-redux-form/dist/index.js' {
  declare module.exports: $Exports<'react-semantic-redux-form/dist/index'>;
}
