// flow-typed signature: 06c66934528e9637f123d5dfabd54aea
// flow-typed version: <<STUB>>/react-epic-spinners_v0.3.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-epic-spinners'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-epic-spinners' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-epic-spinners/dist/react-epic-spinners.cjs' {
  declare module.exports: any;
}

declare module 'react-epic-spinners/dist/react-epic-spinners.cjs.min' {
  declare module.exports: any;
}

declare module 'react-epic-spinners/dist/react-epic-spinners.esm' {
  declare module.exports: any;
}

declare module 'react-epic-spinners/dist/react-epic-spinners.umd' {
  declare module.exports: any;
}

declare module 'react-epic-spinners/dist/react-epic-spinners.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-epic-spinners/dist/react-epic-spinners.cjs.js' {
  declare module.exports: $Exports<'react-epic-spinners/dist/react-epic-spinners.cjs'>;
}
declare module 'react-epic-spinners/dist/react-epic-spinners.cjs.min.js' {
  declare module.exports: $Exports<'react-epic-spinners/dist/react-epic-spinners.cjs.min'>;
}
declare module 'react-epic-spinners/dist/react-epic-spinners.esm.js' {
  declare module.exports: $Exports<'react-epic-spinners/dist/react-epic-spinners.esm'>;
}
declare module 'react-epic-spinners/dist/react-epic-spinners.umd.js' {
  declare module.exports: $Exports<'react-epic-spinners/dist/react-epic-spinners.umd'>;
}
declare module 'react-epic-spinners/dist/react-epic-spinners.umd.min.js' {
  declare module.exports: $Exports<'react-epic-spinners/dist/react-epic-spinners.umd.min'>;
}
