// flow-typed signature: 111e7c4d39298d5651d0d8e8355df11f
// flow-typed version: <<STUB>>/react-localize-redux_v3.5.2/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-localize-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-localize-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-localize-redux/dist/ReactLocalizeRedux' {
  declare module.exports: any;
}

declare module 'react-localize-redux/dist/ReactLocalizeRedux.min' {
  declare module.exports: any;
}

declare module 'react-localize-redux/es/index' {
  declare module.exports: any;
}

declare module 'react-localize-redux/es/localize' {
  declare module.exports: any;
}

declare module 'react-localize-redux/es/LocalizeContext' {
  declare module.exports: any;
}

declare module 'react-localize-redux/es/LocalizeProvider' {
  declare module.exports: any;
}

declare module 'react-localize-redux/es/Translate' {
  declare module.exports: any;
}

declare module 'react-localize-redux/es/utils' {
  declare module.exports: any;
}

declare module 'react-localize-redux/es/withLocalize' {
  declare module.exports: any;
}

declare module 'react-localize-redux/lib/index' {
  declare module.exports: any;
}

declare module 'react-localize-redux/lib/localize' {
  declare module.exports: any;
}

declare module 'react-localize-redux/lib/LocalizeContext' {
  declare module.exports: any;
}

declare module 'react-localize-redux/lib/LocalizeProvider' {
  declare module.exports: any;
}

declare module 'react-localize-redux/lib/Translate' {
  declare module.exports: any;
}

declare module 'react-localize-redux/lib/utils' {
  declare module.exports: any;
}

declare module 'react-localize-redux/lib/withLocalize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-localize-redux/dist/ReactLocalizeRedux.js' {
  declare module.exports: $Exports<'react-localize-redux/dist/ReactLocalizeRedux'>;
}
declare module 'react-localize-redux/dist/ReactLocalizeRedux.min.js' {
  declare module.exports: $Exports<'react-localize-redux/dist/ReactLocalizeRedux.min'>;
}
declare module 'react-localize-redux/es/index.js' {
  declare module.exports: $Exports<'react-localize-redux/es/index'>;
}
declare module 'react-localize-redux/es/localize.js' {
  declare module.exports: $Exports<'react-localize-redux/es/localize'>;
}
declare module 'react-localize-redux/es/LocalizeContext.js' {
  declare module.exports: $Exports<'react-localize-redux/es/LocalizeContext'>;
}
declare module 'react-localize-redux/es/LocalizeProvider.js' {
  declare module.exports: $Exports<'react-localize-redux/es/LocalizeProvider'>;
}
declare module 'react-localize-redux/es/Translate.js' {
  declare module.exports: $Exports<'react-localize-redux/es/Translate'>;
}
declare module 'react-localize-redux/es/utils.js' {
  declare module.exports: $Exports<'react-localize-redux/es/utils'>;
}
declare module 'react-localize-redux/es/withLocalize.js' {
  declare module.exports: $Exports<'react-localize-redux/es/withLocalize'>;
}
declare module 'react-localize-redux/lib/index.js' {
  declare module.exports: $Exports<'react-localize-redux/lib/index'>;
}
declare module 'react-localize-redux/lib/localize.js' {
  declare module.exports: $Exports<'react-localize-redux/lib/localize'>;
}
declare module 'react-localize-redux/lib/LocalizeContext.js' {
  declare module.exports: $Exports<'react-localize-redux/lib/LocalizeContext'>;
}
declare module 'react-localize-redux/lib/LocalizeProvider.js' {
  declare module.exports: $Exports<'react-localize-redux/lib/LocalizeProvider'>;
}
declare module 'react-localize-redux/lib/Translate.js' {
  declare module.exports: $Exports<'react-localize-redux/lib/Translate'>;
}
declare module 'react-localize-redux/lib/utils.js' {
  declare module.exports: $Exports<'react-localize-redux/lib/utils'>;
}
declare module 'react-localize-redux/lib/withLocalize.js' {
  declare module.exports: $Exports<'react-localize-redux/lib/withLocalize'>;
}
