// flow-typed signature: 77b2c2ede7cd54f18ddf5c235612f302
// flow-typed version: <<STUB>>/react-frontload_v1.0.7/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-frontload'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-frontload' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-frontload/example/build/client.bundle' {
  declare module.exports: any;
}

declare module 'react-frontload/example/build/server.bundle' {
  declare module.exports: any;
}

declare module 'react-frontload/example/client' {
  declare module.exports: any;
}

declare module 'react-frontload/example/Layout' {
  declare module.exports: any;
}

declare module 'react-frontload/example/Loader' {
  declare module.exports: any;
}

declare module 'react-frontload/example/NestedComponentsPage' {
  declare module.exports: any;
}

declare module 'react-frontload/example/server' {
  declare module.exports: any;
}

declare module 'react-frontload/example/StateManager' {
  declare module.exports: any;
}

declare module 'react-frontload/example/Todo' {
  declare module.exports: any;
}

declare module 'react-frontload/example/TodoApp' {
  declare module.exports: any;
}

declare module 'react-frontload/example/todoClient' {
  declare module.exports: any;
}

declare module 'react-frontload/example/TodoPage' {
  declare module.exports: any;
}

declare module 'react-frontload/example/todoService' {
  declare module.exports: any;
}

declare module 'react-frontload/example/TodosPage' {
  declare module.exports: any;
}

declare module 'react-frontload/example/webpack/common' {
  declare module.exports: any;
}

declare module 'react-frontload/example/webpack/webpack.config.client' {
  declare module.exports: any;
}

declare module 'react-frontload/example/webpack/webpack.config.server' {
  declare module.exports: any;
}

declare module 'react-frontload/lib/index' {
  declare module.exports: any;
}

declare module 'react-frontload/src/index' {
  declare module.exports: any;
}

declare module 'react-frontload/tests/index.test' {
  declare module.exports: any;
}

declare module 'react-frontload/tests/jestConfig' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-frontload/example/build/client.bundle.js' {
  declare module.exports: $Exports<'react-frontload/example/build/client.bundle'>;
}
declare module 'react-frontload/example/build/server.bundle.js' {
  declare module.exports: $Exports<'react-frontload/example/build/server.bundle'>;
}
declare module 'react-frontload/example/client.js' {
  declare module.exports: $Exports<'react-frontload/example/client'>;
}
declare module 'react-frontload/example/Layout.js' {
  declare module.exports: $Exports<'react-frontload/example/Layout'>;
}
declare module 'react-frontload/example/Loader.js' {
  declare module.exports: $Exports<'react-frontload/example/Loader'>;
}
declare module 'react-frontload/example/NestedComponentsPage.js' {
  declare module.exports: $Exports<'react-frontload/example/NestedComponentsPage'>;
}
declare module 'react-frontload/example/server.js' {
  declare module.exports: $Exports<'react-frontload/example/server'>;
}
declare module 'react-frontload/example/StateManager.js' {
  declare module.exports: $Exports<'react-frontload/example/StateManager'>;
}
declare module 'react-frontload/example/Todo.js' {
  declare module.exports: $Exports<'react-frontload/example/Todo'>;
}
declare module 'react-frontload/example/TodoApp.js' {
  declare module.exports: $Exports<'react-frontload/example/TodoApp'>;
}
declare module 'react-frontload/example/todoClient.js' {
  declare module.exports: $Exports<'react-frontload/example/todoClient'>;
}
declare module 'react-frontload/example/TodoPage.js' {
  declare module.exports: $Exports<'react-frontload/example/TodoPage'>;
}
declare module 'react-frontload/example/todoService.js' {
  declare module.exports: $Exports<'react-frontload/example/todoService'>;
}
declare module 'react-frontload/example/TodosPage.js' {
  declare module.exports: $Exports<'react-frontload/example/TodosPage'>;
}
declare module 'react-frontload/example/webpack/common.js' {
  declare module.exports: $Exports<'react-frontload/example/webpack/common'>;
}
declare module 'react-frontload/example/webpack/webpack.config.client.js' {
  declare module.exports: $Exports<'react-frontload/example/webpack/webpack.config.client'>;
}
declare module 'react-frontload/example/webpack/webpack.config.server.js' {
  declare module.exports: $Exports<'react-frontload/example/webpack/webpack.config.server'>;
}
declare module 'react-frontload/lib/index.js' {
  declare module.exports: $Exports<'react-frontload/lib/index'>;
}
declare module 'react-frontload/src/index.js' {
  declare module.exports: $Exports<'react-frontload/src/index'>;
}
declare module 'react-frontload/tests/index.test.js' {
  declare module.exports: $Exports<'react-frontload/tests/index.test'>;
}
declare module 'react-frontload/tests/jestConfig.js' {
  declare module.exports: $Exports<'react-frontload/tests/jestConfig'>;
}
