// flow-typed signature: 5a163f507f50a7d15a459dfeeba7da42
// flow-typed version: <<STUB>>/@aws-amplify/ui_v^1.0.14/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@aws-amplify/ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@aws-amplify/ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@aws-amplify/ui/dist/aws-amplify-ui' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui/dist/aws-amplify-ui.min' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui/src/index' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@aws-amplify/ui/dist/aws-amplify-ui.js' {
  declare module.exports: $Exports<'@aws-amplify/ui/dist/aws-amplify-ui'>;
}
declare module '@aws-amplify/ui/dist/aws-amplify-ui.min.js' {
  declare module.exports: $Exports<'@aws-amplify/ui/dist/aws-amplify-ui.min'>;
}
declare module '@aws-amplify/ui/src/index.js' {
  declare module.exports: $Exports<'@aws-amplify/ui/src/index'>;
}
declare module '@aws-amplify/ui/webpack.config.js' {
  declare module.exports: $Exports<'@aws-amplify/ui/webpack.config'>;
}
